[project]
name = "fixedwidth"
version = "2025.08.30"
description = "To-way fixed-width <--> Python dict converter"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
